### PR TITLE
#54  #48 refactor codebase and resize canvas

### PR DESCRIPTION
**Pull request by mewiemers**
- change backgroundimage in detail pages
- throw out grid structure and change to position the images via `positon`
- add resize canvas function `handleResize` to `Canvas.tsx`
- replace arrow component, set new arrows as `img` 
- change positioning of `AnimalCard`

### CODE REVIEW

**Comment by HorstFrank** [comment]
LG!

**Review by mrana17 — APPROVED** [review]
LGTM 🚀

**Review by christophvogel — APPROVED** [review]
LGTM 💯

**Review by HorstFrank — APPROVED** [review]
LganzokayFM

**Pull request merged**
